# common: &common
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: tyler
#   password: 123456

# development:
#   <<: *common
#   database: eversite_dev

# test:
#   <<: *common
#   database: eversite_test